name: Monitor Workflows and Create Issues

on:
  workflow_run:
    workflows: ["docker-image.yml", "python-app.yml"]
    types:
      - completed

jobs:
  monitor_and_create_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check Workflow Status
        id: check_status
        run: echo "::set-output name=workflow_status::${{ github.event.workflow_run.conclusion }}"

      - name: Get Repository Name
        id: repo_name
        run: echo "::set-output name=repo_name::${{ github.repository }}"

      - name: Get Initiator Username
        id: initiator
        run: echo "::set-output name=username::${{ github.actor }}"

      - name: Create Issue on Workflow Failure
        if: steps.check_status.outputs.workflow_status == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_CUSTOM_PAT }}
        run: |
          WORKFLOW_NAME="${{ github.event.workflow_run.workflow }}"
          REPO_NAME="${{ steps.repo_name.outputs.repo_name }}"
          INITIATOR_USERNAME="${{ steps.initiator.outputs.username }}"
          ISSUE_TITLE="Workflow '${WORKFLOW_NAME}'"
          ISSUE_BODY="The workflow '${WORKFLOW_NAME}' has failed in the repository '${REPO_NAME}'\n\nInitiator: @${INITIATOR_USERNAME}"

          # Create the issue using the GitHub API
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -d '{"title":"'"$ISSUE_TITLE"'","body":"'"$ISSUE_BODY"'"}' \
          "https://api.github.com/repos/${REPO_NAME}/issues"
