name: Collect severity from JSON file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Collect severity from JSON file
        run: |
          npm install jq

          # Get the severity from the JSON file
          severity=$(jq -r '.severity' < results.json)

          # Output the severity
          echo "Severity: $severity"

      - name: Upload severity to artifact
        uses: actions/upload-artifact@v2
        with:
          name: severity
          path: ${{ steps.collect-severity.outputs.severity }}
