name: Convert JSON to HTML

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Convert JSON to HTML
        run: |
          # Read the JSON file
          json=$(cat results.json)

          # Convert JSON to HTML table using a tool like jq
          html=$(echo "$json" | jq -r '["<table>"] + (.[] | ["<tr>", "<td>", .field1, "</td>", "<td>", .field2, "</td>", "</tr>"]) + ["</table>"] | join("")')

          # Write the HTML table to a file
          echo "$html" > results.html

      - name: Upload Veracode results
        uses: actions/upload-artifact@v3
        with:
          name: results_html
          path: results.html
