name: Check Severity

on:
  push:
    branches:
      - main  # Replace with your branch name or desired trigger

jobs:
  check_severity:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get results.json file
      run: |
        cat results.json

    - name: Run the script
      run: |
        # Load the JSON file directly
        # data=$(cat results.json)

        severity_4=$(grep -i "severity": "4" results.json || true)
        severity_5=$(grep -i "severity": "5" results.json || true)

        # # Initialize variables for severity 4 and severity 5 counts
        # severity_4=$(echo "$data" | grep -c '"severity": "4"')
        # severity_5=$(echo "$data" | grep -c '"severity": "5"')

        # Print the counts for severity 4 and severity 5
        echo "Severity 4 Count: $severity_4"
        echo "Severity 5 Count: $severity_5"

        # Check if severity 4 count is greater than 3 and print
        if [ "$severity_4" -gt "3" ]; then
            echo "High severity: $severity_4"
        fi

        # Check if severity 5 count is greater than 3 and print
        if [ "$severity_5" -gt "3" ]; then
            echo "High severity: $severity_5"
        fi
