name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  convert-json-to-html:
    runs-on: ubuntu-latest

    inputs:
      json-file:
        type: string

    steps:
      - uses: actions/checkout@v3

      - name: Convert JSON to HTML
        uses: your-username/convert-json-to-html@v1
        with:
          json-file: ${{ inputs.json-file }}

      - name: Save HTML output
        run: echo "${{ steps.convert-json-to-html.outputs.html }}" > output.html

      - name: Upload HTML Table to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output_html
          path: output.html
