name: Convert JSON to HTML Table with Mentions

on:
  push:
    branches:
      - main

jobs:
  convert-json-to-html-table-with-mentions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install json2table

      - name: Convert JSON to HTML Table with Mentions
        run: |
          import json
          from json2table import write_table

          # Load the JSON data
          json_data = json.load(open('result.json'))

          # Highlight mentions
          for mention in json_data['mentions']:
            json_data[mention] = '<strong>{}</strong>'.format(json_data[mention])

          # Write the HTML table
          write_table(json_data, 'table.html')

      - name: Upload HTML Table to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: table.html
          path: table.html
