name: Check Severity

on:
  push:
    branches:
      - main  # Replace with your branch name or desired trigger

jobs:
  check_severity:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get results.json file
      run: |
        pip install json2table
        python json-html-table.py

    - name: Upload HTML Table to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output_html 
        path: test.html # The created file's name is output.html. Name cannot be changed

    - name: Run the script
      run: |
        json_data=$(cat results.json)
        # Extract the severity 4 and severity 5 findings and count them
        severity_4_count=$(echo "$json_data" | jq '.findings[] | select(.severity == 4) | .severity' | wc -l)
        severity_5_count=$(echo "$json_data" | jq '.findings[] | select(.severity == 5) | .severity' | wc -l)
        
        # Print the High severity & Very High severity
        echo "Found $severity_4_count issues of High severity."
        echo "Found $severity_5_count issues of Very High severity."
        
         # Check if either severity 4 or severity 5 counts are greater than 3 and print
        if [ "$severity_4_count" -gt 5 ] || [ "$severity_5_count" -gt 3 ]; then
            echo "Either high or very high severity is greater than necessary.Check the artifect for Veracode results. or log"
            exit 1  # Fail the workflow
        fi
        

