name: Convert JSON to SARIF and upload to GitHub

on:
  push:
    branches:
      - main

jobs:
  convert-json-to-sarif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Convert JSON to SARIF
        uses: garethr/snyk-to-sarif@master
        with:
          input: results.json

      - name: Upload HTML Table to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: snyk_sarif
          path: snyk.sarif
