name: Convert JSON to HTML

on:
  push:
    branches:
      - main

jobs:
  json-to-html:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Convert JSON to HTML
        run: |
          # Install the necessary dependencies
          sudo apt install python3-pip
          pip3 install json-to-html

          # Read the JSON file
          with open("data.json", "r") as f:
            json_data = json.load(f)

          # Convert the JSON data to HTML
          html_data = json_to_html.convert(json_data)

          # Write the HTML data to a file
          with open("output.html", "w") as f:
            f.write(html_data)

      - name: Upload HTML Table to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output_html
          path: output.html
