name: update_test

on:
  push:
    branches:
      - main

jobs:
  build_an:
    name: testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Convert to sarif
        run: |
          sudo pip install joern2sarif
          joern2sarif -t ocular -i ${GITHUB_WORKSPACE}\results.json -o ${GITHUB_WORKSPACE}\veracode-findings.sarif
        env:
          WORKSPACE: ""
      
      - name: Upload Veracode results
        uses: actions/upload-artifact@v3
        with:
          name: veracode-results-sarif
          path: veracode-findings.sarif
      
      