name: Convert JSON to HTML

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Convert JSON to HTML
        run: |
          # Read the JSON file
          json=$(cat results.json)

          # Generate the HTML table header
          header="<tr>"
          for key in $(echo "$json" | jq -r '.[0] | keys_unsorted[]'); do
            header+="<th>$key</th>"
          done
          header+="</tr>"

          # Generate the HTML table rows
          rows=""
          for row in $(echo "$json" | jq -r '.[] | @base64'); do
            _jq() {
              echo "$row" | base64 --decode | jq -r "$1"
            }
            rows+="<tr>"
            for key in $(echo "$json" | jq -r '.[0] | keys_unsorted[]'); do
              value=$(_jq ".$key")
              rows+="<td>$value</td>"
            done
            rows+="</tr>"
          done

          # Generate the complete HTML table
          html="<table>$header$rows</table>"

          # Write the HTML table to a file
          echo "$html" > results.html

          # Print the HTML table
          cat results.html


      - name: Upload Veracode results
        uses: actions/upload-artifact@v3
        with:
          name: results_html
          path: results.html
