name: Python package

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get Initiator Username
        id: initiator
        run: echo "::set-output name=username::${{ github.actor }}"

      - name: Get Branch Name
        id: branch
        run: echo "::set-output name=branch::${{ github.ref }}"

      - name: Get Commit Messages
        id: commit_messages
        run: |
          COMMIT_MESSAGES=$(git log --format=%B -n 1)
          echo "::set-output name=commit_messages::${COMMIT_MESSAGES}"

      - name: Fetch Assignees from JSON
        id: fetch_assignees
        run: |
          # Fetch the JSON file containing assignees from your repository
          ASSIGNEE_JSON=$(cat assignees.json)
          echo "::set-output name=assignees::${ASSIGNEE_JSON}"

      - name: Create GitHub Issue
        env:
          GITHUB_TOKEN: ${{ secrets.MY_CUSTOM_PAT }}
        run: |
          ISSUE_TITLE="Workflow Failure: python-app.yml workflow"
          INITIATOR_USERNAME="${{ steps.initiator.outputs.username }}"
          BRANCH_NAME="${{ steps.branch.outputs.branch }}"
          COMMIT_MESSAGES="${{ steps.commit_messages.outputs.commit_messages }}"
          
          # Parse the JSON array of assignees
          ASSIGNEE_JSON="${{ steps.fetch_assignees.outputs.assignees }}"
          ASSIGNEE_ARRAY=$(echo "${ASSIGNEE_JSON}" | jq -r '.[]')

          # Create the issue body with the parsed assignees
          ASSIGNEE_STRING=""
          for assignee in $ASSIGNEE_ARRAY; do
            ASSIGNEE_STRING="${ASSIGNEE_STRING}\"${assignee}\","
          done
          # Remove the trailing comma
          ASSIGNEE_STRING="${ASSIGNEE_STRING%,}"

          # Replace newlines in commit messages with <br> for formatting in the issue body.
          COMMIT_MESSAGES_HTML=$(echo "${COMMIT_MESSAGES}" | awk '{printf "%s<br>",$0}')

          ISSUE_BODY="The workflow has failed. Initiator: @${INITIATOR_USERNAME}, Branch: ${BRANCH_NAME}\n\nCommit Messages:\n${COMMIT_MESSAGES_HTML}"

          # Create the issue using the GitHub API and assignees
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -d '{"title":"'"$ISSUE_TITLE"'","body":"'"$ISSUE_BODY"'","assignees":['"${ASSIGNEE_STRING}"']}' \
          "https://api.github.com/repos/Teebra/Tic-Tac-Toe-Game/issues"