# python-app.yml

name: Python package

on:
  pull_request:
    branches:
      - '*' 
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          if ! pytest -v test.py; then
            echo "Tests failed, setting workflow status to failure"
            echo "::set-output name=workflow_status::failure"
      
  check_workflow_status:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() }} # This ensures the job always runs but might not produce an outcome
    steps:
      - name: Set Workflow Status
        id: set_workflow_status
        run: echo "::set-output name=workflow_status::${{ env.WORKFLOW_STATUS }}"

  trigger_monitoring:
    runs-on: ubuntu-latest
    needs: check_workflow_status
    if: ${{ needs.check_workflow_status.outputs.workflow_status == 'failure' }}
    steps:
      - name: Trigger Monitoring Workflow
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const token = github.token;
            const owner = github.context.repo.owner;
            const repo = github.context.repo.repo;
            const workflowFileName = "issue_create.yml"; // Update with the correct filename of your monitoring workflow
            
            const response = await github.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: workflowFileName,
            });
            
            console.log(response);
